spring:
  application:
    name: org-tg-bot

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  cache:
    type: caffeine
    cache-names:
      - states_cache
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}

logging:
  level:
    root: INFO
    com.orgtgbot: DEBUG

gemini:
  api-key: ${GEMINI_API_KEY}