spring:
  application:
    name: org-tg-bot

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
    allowed-users:
      - 5227547972
      - 5022879821

logging:
  level:
    root: INFO
    com.orgtgbot: DEBUG