package com.orgtgbot.bot.state;

import lombok.Getter;

@Getter
public enum UserState {
    NONE,

    PROBEG_MORNING_MONDAY,
    PROBEG_EVENING_MONDAY,
    PROBEG_TOTAL_MONDAY,
    ROUTE_MONDAY,
    PROBEG_MORNING_TUESDAY,
    PROBEG_EVENING_TUESDAY,
    PROBEG_TOTAL_TUESDAY,
    ROUTE_TUESDAY,
    PROBEG_MORNING_WEDNESDAY,
    PROBEG_EVENING_WEDNESDAY,
    PROBEG_TOTAL_WEDNESDAY,
    ROUTE_WEDNESDAY,
    PROBEG_MORNING_THURSDAY,
    PROBEG_EVENING_THURSDAY,
    PROBEG_TOTAL_THURSDAY,
    ROUTE_THURSDAY,
    PROBEG_MORNING_FRIDAY,
    PROBEG_EVENING_FRIDAY,
    PROBEG_TOTAL_FRIDAY,
    ROUTE_FRIDAY
}
